/********************************************************************
* propDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error propDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablepropDict();
extern void G__cpp_setup_inheritancepropDict();
extern void G__cpp_setup_typetablepropDict();
extern void G__cpp_setup_memvarpropDict();
extern void G__cpp_setup_globalpropDict();
extern void G__cpp_setup_memfuncpropDict();
extern void G__cpp_setup_funcpropDict();
extern void G__set_cpp_environmentpropDict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "InteractionInfo.h"
#include "NeutrinoEvent.h"
#include "Propagator.h"
#include "WorldModel.h"
#include "BedmapTable.h"
#include "RayTracer.h"
#include "RFEvent.h"
#include "SubWaveInfo.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__propDictLN_TClass;
extern G__linked_taginfo G__propDictLN_TBuffer;
extern G__linked_taginfo G__propDictLN_TMemberInspector;
extern G__linked_taginfo G__propDictLN_TObject;
extern G__linked_taginfo G__propDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__propDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__propDictLN_TClonesArray;
extern G__linked_taginfo G__propDictLN_TVector3;
extern G__linked_taginfo G__propDictLN_RyansCons;
extern G__linked_taginfo G__propDictLN_RyansConscLcLBedmapType_t;
extern G__linked_taginfo G__propDictLN_RyansConscLcLCrust2Type_t;
extern G__linked_taginfo G__propDictLN_RyansConscLcLInteractionType_t;
extern G__linked_taginfo G__propDictLN_RyansConscLcLParticleType_t;
extern G__linked_taginfo G__propDictLN_RyansConscLcLMaterialType_t;
extern G__linked_taginfo G__propDictLN_InteractionInfo;
extern G__linked_taginfo G__propDictLN_NeutrinoEvent;
extern G__linked_taginfo G__propDictLN_TRandom;
extern G__linked_taginfo G__propDictLN_TF1;
extern G__linked_taginfo G__propDictLN_Propagator;
extern G__linked_taginfo G__propDictLN_BedmapTable;
extern G__linked_taginfo G__propDictLN_WorldModel;
extern G__linked_taginfo G__propDictLN_SubWaveInfo;
extern G__linked_taginfo G__propDictLN_RFEvent;
extern G__linked_taginfo G__propDictLN_RayTracer;

/* STUB derived class for protected member access */
